[package]
name = "cryptolens-examples"
version = "0.1.0"
authors = ["rust"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#cryptolens = { path = "../cryptolens", version = "0.0.1" }
cryptolens = "0.0.1"
